# Generated by Django 2.2.19 on 2023-01-12 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20230108_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('text', models.TextField(help_text='Введите текст поста', verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_rname', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'default_related_name': 'comment_rname',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_rname', to='posts.Comment', verbose_name='Комментарий'),
        ),
    ]
